# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "pypy"

install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python test_glibc.py -v
